---

    before_script:
      - apt update -qy
      - apt install -y python-dev python-pip git sshpass
      - git submodule update --init
      - pip install --upgrade ansible ansible-lint
      - ansible --version
      - ansible-lint --version
      - echo "$ANSIBLE_PASS" > ".tmpass"
      - cat .tmpass
      - sed -i 's/{{ SSHROOT }}/"$SSHROOT"/' secrets.yml
      - ansible-vault encrypt secrets.yml --vault-password-file .tmpass
  
    stages:
      - ansible-syntax-check
      - ansible-lint

    ansible-syntax-check:
      stage: ansible-syntax-check
      script:
        - ansible-playbook --inventory inventory --syntax-check main.yaml --vault-password-file .tmpass
        - rm .tmpass
  
  
    ansible-lint:
      stage: ansible-lint
      script:
        - ansible-lint main.yaml 
      allow_failure: true
  