---
    - name: Upgrading distribution
        apt:
            upgrade: dist
    
    - name: Updating cache
        apt:
            update_cache: yes
        
    - name: Installing dependancies for Docker
        apt: name={{item}} state=present
        with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg2
            - software-properties-common
        
    - name: Adding Docker's official GPG key
        shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        args:
          warn: no
        
    - name: Set distribution
        command: lsb_release -cs
        register: distrib
        
    - name: Setting up the stable repository
        apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/debian {{distrib.stdout}} stable
            state: present
        
    - name: Updating cache
        apt:
            update_cache: yes
        
    - name: Installing Docker
        apt: name={{item}} state=present
        with_items:
            - docker-ce
            - docker-ce-cli
            - containerd.io
        
    - name: uname -s
        command: uname -s
        register: unames
        
    - name: uname -m
        command: uname -m
        register: unamem
        
    - name: Downloading latest stable docker-compose
        command: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{unames.stdout}}-{{unamem.stdout}}" -o /usr/local/bin/docker-compose
        
    - name: Applying executable permissions to the binary
        command: chmod +x /usr/local/bin/docker-compose